name: Deploy site
on:
  push:
    branches:
      - main
jobs:
  build_production_image:
    if: github.ref == 'refs/heads/main'
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{vars.IMAGE_NAME}}:latest
          build-args: |
            MONGODB_URI=${{ secrets.MONGODB_URI }}

  deploy_production:
    if: github.ref == 'refs/heads/main'
    environment: production
    runs-on: ubuntu-latest
    needs: build_production_image
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_SERVER_HOST }}
          username: ${{ secrets.REMOTE_SERVER_HOSTNAME }}
          key: ${{ secrets.REMOTE_SERVER_SSH_KEY }}
          script: |
            cd /home/ec2-user/app  
            sudo git pull origin main || true
            sudo docker stop $(docker ps -q)
            sudo docker rm $(docker ps -aq)
            sudo ./run.sh
